[package]
name = "subscription_test"
version = "0.1.0"
edition = "2021"

[dependencies]
iced = { version = "0.12", features = [ "tokio" ] }
tokio = { version = "1", features = ["full"] }
rand = "0.8.5"
